### ISSUE TITLE
2019秋招

### ISSUE THREAD

**Issue by HolyZheng** [HolyZheng/-JavaScript-#1]
### 可投递 
1. 顺丰科技   7.12-7.28
***
2. 网易互联网
    - 内推7.17-8.8
笔试8.11
面试8月下旬

    - 网申8.9-9.5
笔试9.8
九月中下旬
***
3. 网易游戏                                      
    - 内推时间8.9号截止
提前批笔试/面试  8.8/8月中旬
   
    - 简历截止9.5
非提前批笔试/面试  9月上旬/9月下旬                                   
**8.1投递**
***
5. 百度
    - 提前批8.10前投递
***
5. 阿里巴巴   
网申时间7.16-8.17      
内推时间7.16-8.17        
笔试时间8.29-31
面试 9月中旬                              
**8.5投递**
***
6. 京东          
    - 提前批内推8.20截止
8.30号前安排面试 
    - 网申时间 7.13-9.6          
笔试9.9
面试 9月中旬 
**8.10投递**
***
7. 唯品会       
网申时间 7.13-9.12     
内推时间 8.31截止
笔试9月15      
面试9月下旬                                  
**8.20投递**
***
8. 好未来       7月初到8月初
***
9. 腾讯
- 提前批 7月25-9月8日
- 面试 9月14日前
***
10. 多益网络
8.11笔试

### 已投递
1. 网易互联网 内推码
2. 顺丰科技     内推码   无消息
3. 百度             提前批
4. 百度            度秘
5. 京东            猎奇（未回复）已网申
6. 阿里            内推码 
7. 苏宁  南京    内推码  放弃
8. 携程           内推  1377561817@qq.com
9. 好未来       内推   forever_gcg
10. 欢聚时代   内推  1192153449@qq.com
11. 爱奇艺       内推  1757548534@qq.com
12. 有赞  杭州  内推  
13. 三七互娱    内推 ljh684616@sina.com

## 挂
1. cvte             内推码   笔试挂
2. 多益网络     内推码   笔试挂

**Comment by univeryinli** [comment]
请问哪里可以搞到网易内推码呢？

**Comment by HolyZheng** [comment]
抱歉这是19年的总结
